on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Set up Git
        run: git config --global user.email "wouter_peere@hotmail.com" && git config --global user.name "GitHub Actions"
      - name: Set default branch.
        run: git remote set-head origin --auto
        shell: bash
      - name: Update version in version file and commit
        run: |
          echo "version: ${{ steps.vars.outputs.tag }}" > versions.txt
          git add versions.txt
          git commit -m "Update version to ${{ github.event.release.tag_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}