name: CI test-pypi

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dev-tests:
    name: Development tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          python -m pip install pytest
      - name: Test with pytest
        run: pytest test.py

  create-tag:
    name: Set tag
    runs-on: ubuntu-latest
    needs: dev-tests
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - name: Set up Git
        run: git config --global user.email "wouter_peere@hotmail.com" && git config --global user.name "GitHub Actions"
      - name: Update version in version file and commit
        run: |
          echo "${{ steps.vars.outputs.tag }}" > VERSION.txt
          git add VERSION.txt 
          git commit -am "Update version to ${{ steps.vars.outputs.tag }}"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    needs: create-tag

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    needs: build
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/experiment-thesis2

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: __token__
          password: ${{ secrets.TESTPYPI }}
